global:

route:
  receiver: 'slack'

receivers:
  - name: "slack"
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxxxx/xxxxx/xxxxxx'
        send_resolved: true
        channel: 'general'
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
