version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    hostname: "prometheus"
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - 29486:9090
    restart: always
    networks:
      - promnet

  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: "alertmanager"
    hostname: "alertmanager"
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 38485:9093
    restart: always
    networks:
      - promnet

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: "node_exporter"
    hostname: "node_exporter"
    command:
      - '--path.rootfs=/host'
    restart: always
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: "cadvisor"
    hostname: "cadvisor"
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=30s'
      - '-disable_metrics=disk'
    ports:
      - 56969:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - 28485:3000
    restart: always
    networks:
      - promnet

networks:
  promnet:
    driver: bridge